# Generated by Django 4.2.3 on 2024-03-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('licence_number', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('car_in_charge_of', models.CharField(max_length=100)),
                ('company_from', models.CharField(max_length=100)),
            ],
        ),
    ]
