# Generated by Django 4.2.3 on 2024-03-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='i am mercy achieng i am a transcountry driver with 4years of experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Okeyo Mercy(Default)', max_length=100, null=True),
        ),
    ]
