# Generated by Django 4.2.3 on 2024-03-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0005_message_category_message_is_read_message_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
